/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ChucNang;

import vovanngoc_n21dcat035.*;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author ngocn
 */
public class GDChucNang extends javax.swing.JPanel {

    /**
     * Creates new form NutChucNang
     */

    public GDChucNang() {
        
        initComponents();
    }

    public void initEvent(Action event, int row) {
        Sua.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                event.sua(row);
            }
        });
        Xoa.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                event.xoa(row);
            }
        });
        Xem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                event.xem(row);
            }
    });
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Xoa = new javax.swing.JLabel();
        Sua = new javax.swing.JLabel();
        Xem = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(89, 20));

        Xoa.setText("Xóa");
        Xoa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                XoaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Xoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                XoaFocusGained(evt);
            }
        });
        Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XoaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                XoaMouseReleased(evt);
            }
        });
        Xoa.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                Xoa.setForeground(Color.BLUE);
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                Xoa.setForeground(Color.BLACK);
                setCursor(Cursor.getDefaultCursor());
            }
        });

        Sua.setText("Sửa");
        Sua.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SuaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Sua.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                Sua.setForeground(Color.BLUE);
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                Sua.setForeground(Color.BLACK);
                setCursor(Cursor.getDefaultCursor());
            }
        });

        Xem.setText("Xem");
        Xem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                XemAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Xem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                Xem.setForeground(Color.BLUE);
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                Xem.setForeground(Color.BLACK);
                setCursor(Cursor.getDefaultCursor());
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Xem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Xoa)
                .addComponent(Sua)
                .addComponent(Xem))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XoaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_XoaFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_XoaFocusGained

    private void XoaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_XoaAncestorAdded
            
        
    }//GEN-LAST:event_XoaAncestorAdded

    private void SuaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SuaAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SuaAncestorAdded

    private void XemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_XemAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_XemAncestorAdded

    private void XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XoaMouseClicked
//        XuLySQL.xoaSV(GiaoDienChinh.maChon);
//        JOptionPane.showMessageDialog(this, "Xóa thành công!!!");
    }//GEN-LAST:event_XoaMouseClicked

    private void XoaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XoaMouseReleased

    }//GEN-LAST:event_XoaMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sua;
    private javax.swing.JLabel Xem;
    private javax.swing.JLabel Xoa;
    // End of variables declaration//GEN-END:variables
}
