-- Tạo cơ sở dữ liệu DSSINHVIEN
USE master;
GO
IF DB_ID('DSSINHVIEN') IS NULL
	CREATE DATABASE DSSINHVIEN;
	GO

-- Sử dụng cơ sở dữ liệu DSSINHVIEN
USE DSSINHVIEN;
GO

-- Tạo bảng SINHVIEN
IF OBJECT_ID('SINHVIEN', 'U') IS NOT NULL
BEGIN
DROP TABLE SINHVIEN;

    -- Tạo bảng SINHVIEN
    CREATE TABLE SINHVIEN (
        MASV NVARCHAR(10) NOT NULL,
        HOTEN NVARCHAR(50) NOT NULL,
		NGAYSINH DATE NOT NULL,
		GIOITINH BIT NOT NULL,
        SDT NVARCHAR(10) NOT NULL,
        MAIL NVARCHAR(50) NOT NULL,
        CONSTRAINT [PK_SINHVIEN] PRIMARY KEY CLUSTERED ([MASV] ASC) WITH (
            PAD_INDEX = OFF,
            STATISTICS_NORECOMPUTE = OFF,
            IGNORE_DUP_KEY = OFF,
            ALLOW_ROW_LOCKS = ON,
            ALLOW_PAGE_LOCKS = ON
        ) ON [PRIMARY]
    ) ON [PRIMARY];
END
GO
   INSERT [dbo].[SINHVIEN] ([MASV], [HOTEN], [NGAYSINH], [GIOITINH], [SDT], [MAIL]) VALUES (N'N21DCAT035', N'Võ Văn Ngọc', '2003-09-15', 1, N'0945437279', N'N21DCAT035@student.ptithcm.edu.vn')