/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vovanngoc_n21dcat035;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ngocn
 */
public class GDSua extends javax.swing.JFrame {

    /**
     * Creates new form GDSua
     */
    private Point initialClick;
    public GDSua() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                // Lấy tọa độ chuột khi nhấn
                initialClick = e.getPoint();
            }
            
        });
        jPanel1.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                // Lấy tọa độ chuột khi kéo
                int x = getLocation().x + e.getX() - initialClick.x;
                int y = getLocation().y + e.getY() - initialClick.y;

                // Di chuyển cửa sổ đến vị trí mới
                setLocation(x, y);
            }
        });
    }

    
    
    public JTextField getEditHoTen() {
        return editHoTen;
    }

    public JTextField getEditMail() {
        return editMail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public JTextField getEditSDT() {
        return editSDT;
    }

    public static boolean namNhuan(int y) {
        if ((y % 4 == 0 && y % 100 != 0) || y % 400 == 0) {
            return true;
        } else {
            return false;
        }
    }
    
    public void setThongTin(int row) {
        String ns = (String) GiaoDienChinh.dtm.getValueAt(row, 2);
        String[] ngay = ns.split("-");
        editMaSV.setText("Mã Sinh Viên: " + (String) GiaoDienChinh.dtm.getValueAt(row, 0));
        editHoTen.setText((String) GiaoDienChinh.dtm.getValueAt(row, 1));
        editNgay.setSelectedItem(ngay[2]);
        editThang.setSelectedItem(ngay[1]);
        editNam.setSelectedItem(ngay[0]);
        if((Byte) GiaoDienChinh.dtm.getValueAt(row, 3) == 1) {
            editGTNam.setSelected(true);
            editGTNu.setSelected(false);
        } else {
            editGTNu.setSelected(true);
            editGTNam.setSelected(false);
        }
        editSDT.setText((String) GiaoDienChinh.dtm.getValueAt(row, 4));
        editMail.setText((String) GiaoDienChinh.dtm.getValueAt(row, 5));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NutHuy = new javax.swing.JButton();
        NutSua = new javax.swing.JButton();
        editHoTen = new javax.swing.JTextField();
        editNgay = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        editThang = new javax.swing.JComboBox<>();
        editNam = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        editGTNam = new javax.swing.JRadioButton();
        editGTNu = new javax.swing.JRadioButton();
        editSDT = new javax.swing.JTextField();
        editMail = new javax.swing.JTextField();
        editMaSV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        jPanel1.setToolTipText("");
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SỬA THÔNG TIN SINH VIÊN");

        NutHuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NutHuy.setText("Hủy");
        NutHuy.setMargin(new java.awt.Insets(3, 3, 3, 3));
        NutHuy.setMaximumSize(new java.awt.Dimension(38, 28));
        NutHuy.setMinimumSize(new java.awt.Dimension(38, 28));
        NutHuy.setPreferredSize(new java.awt.Dimension(60, 27));
        NutHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutHuyActionPerformed(evt);
            }
        });

        NutSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NutSua.setText("Lưu");
        NutSua.setMargin(new java.awt.Insets(3, 3, 3, 3));
        NutSua.setMaximumSize(new java.awt.Dimension(38, 28));
        NutSua.setMinimumSize(new java.awt.Dimension(38, 28));
        NutSua.setPreferredSize(new java.awt.Dimension(60, 27));
        NutSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutSuaActionPerformed(evt);
            }
        });

        editHoTen.setForeground(new java.awt.Color(153, 153, 153));
        editHoTen.setText("Nhập Họ Và Tên");
        editHoTen.setToolTipText("Nhập Họ Và Tên");
        editHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editHoTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editHoTenFocusLost(evt);
            }
        });
        editHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHoTenActionPerformed(evt);
            }
        });

        editNgay.setMaximumRowCount(32);
        editNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        editNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNgayActionPerformed(evt);
            }
        });
        editNgay.setMaximumRowCount(10);
        for(int i = 1; i <= 31; i++){
            if(i < 10) editNgay.addItem("0" + String.valueOf(i));
            else editNgay.addItem(String.valueOf(i));
        }

        jLabel2.setText("Ngày Sinh:");

        editThang.setMaximumRowCount(13);
        editThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng" }));
        editThang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editThangFocusGained(evt);
            }
        });
        editThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editThangActionPerformed(evt);
            }
        });
        for(int i = 1; i <= 12; i++){
            if(i < 10) editThang.addItem("0" + String.valueOf(i));
            else editThang.addItem(String.valueOf(i));
        }
        editThang.setMaximumRowCount(10);

        editNam.setMaximumRowCount(100);
        editNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm" }));
        editNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNamActionPerformed(evt);
            }
        });
        for(int i = 0; i <= 100; i++){
            editNam.addItem(String.valueOf(2023 - i));
        }
        editNam.setMaximumRowCount(10);

        jLabel3.setText("Giới Tính:");

        editGTNam.setText("Nam");
        editGTNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGTNamActionPerformed(evt);
            }
        });

        editGTNu.setText("Nữ");
        editGTNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGTNuActionPerformed(evt);
            }
        });

        editSDT.setForeground(new java.awt.Color(153, 153, 153));
        editSDT.setText("Nhập Số Điện Thoại");
        editSDT.setToolTipText("Nhập Số Điện Thoại");
        editSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editSDTFocusLost(evt);
            }
        });
        editSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSDTActionPerformed(evt);
            }
        });

        editMail.setForeground(new java.awt.Color(153, 153, 153));
        editMail.setText("Nhập Mail");
        editMail.setToolTipText("Nhập Mail");
        editMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editMailFocusLost(evt);
            }
        });
        editMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMailActionPerformed(evt);
            }
        });

        editMaSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editMaSV.setText("Mã sinh viên: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editHoTen)
                    .addComponent(editSDT)
                    .addComponent(editMail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editThang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editNam, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editGTNam)
                        .addGap(18, 18, 18)
                        .addComponent(editGTNu)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NutSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NutHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(editMaSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editGTNam)
                    .addComponent(editGTNu)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(editNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editMail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NutHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NutSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded

    }//GEN-LAST:event_jPanel1AncestorAdded

    private void NutSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutSuaActionPerformed
String sdtChuan = "[0-9]{10}";
        String mailChuan = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        if("Nhập Họ Và Tên".equals(editHoTen.getText()) || "Ngày".equals(editNgay.getSelectedItem()) 
                || "Tháng".equals(editThang.getSelectedItem()) || "Năm".equals(editNam.getSelectedItem()) 
                || (!editGTNu.isSelected() && !editGTNam.isSelected()) || "Nhập Số Điện Thoại".equals(editSDT.getText()) 
                || "Nhập Mail".equals(editMail.getText())){
            JOptionPane.showMessageDialog(this, "Không để trống thông tin!!!");
        }else if(!editSDT.getText().matches(sdtChuan)){
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng!!!");
        }else if(!editMail.getText().matches(mailChuan)){
            JOptionPane.showMessageDialog(this, "Mail không đúng định dạng!!!");
        }
        else{
            String ns = editNam.getSelectedItem() + "-" + editThang.getSelectedItem() + "-" + editNgay.getSelectedItem();
            byte gt;
            if(editGTNam.isSelected()) gt = 1;
            else gt = 0;
            XuLySQL.suaSV(editMaSV.getText().substring(14), editHoTen.getText(), ns, gt, editSDT.getText(), editMail.getText());
            if(XuLySQL.loiSua == 1){
                JOptionPane.showMessageDialog(this, "Số điện thoại " + editSDT.getText() + " đã tồn tại!!!");
            }else if(XuLySQL.loiSua == 2){
                JOptionPane.showMessageDialog(this, "Mail " + editMail.getText() + " đã tồn tại!!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Sửa thành công!!!");
                dispose();
                editHoTen.setText("");
                editNgay.setSelectedItem("");; editThang.setSelectedItem(""); editNam.setSelectedItem("");
                editGTNam.setSelected(false); editGTNu.setSelected(false); editSDT.setText(""); editMail.setText("");
            }
        }
    }//GEN-LAST:event_NutSuaActionPerformed

    private void NutHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutHuyActionPerformed
        dispose();
    }//GEN-LAST:event_NutHuyActionPerformed

    private void editHoTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editHoTenFocusGained
        if(editHoTen.getText().equals("Nhập Họ Và Tên")){
            editHoTen.setText("");
            editHoTen.setForeground(new Color(40,40,40));
        }
    }//GEN-LAST:event_editHoTenFocusGained

    private void editHoTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editHoTenFocusLost
        if(editHoTen.getText().equals("")){
            editHoTen.setText("Nhập Họ Và Tên");
            editHoTen.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_editHoTenFocusLost

    private void editHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editHoTenActionPerformed

    private void editNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNgayActionPerformed

    private void editThangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editThangFocusGained

    }//GEN-LAST:event_editThangFocusGained

    private void editThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editThangActionPerformed
        String s = "Ngày"; int x = 29;
        if(!"Ngày".equals(editNgay.getSelectedItem()))
        s = (String) editNgay.getSelectedItem();
        if ("02".equals(editThang.getSelectedItem())) {
            if(!"Năm".equals(editNam.getSelectedItem()))
            x = namNhuan(Integer.parseInt((String) editNam.getSelectedItem())) ? 29 : 28;
            editNgay.removeAllItems();
            editNgay.addItem("Ngày");

            for (int i = 1; i <= x; i++) {
                String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                editNgay.addItem(dayStr);
            }

        }
        var t31 = Arrays.asList("01", "03", "05", "07", "08", "10", "12");
        if (t31.contains(editThang.getSelectedItem())) {
            editNgay.removeAllItems();
            editNgay.addItem("Ngày");
            for (int i = 1; i <= (x = 31); i++) {
                String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                editNgay.addItem(dayStr);
            }
        }
        var t30 = Arrays.asList("04", "06", "09", "11");
        if (t30.contains(editThang.getSelectedItem())) {
            editNgay.removeAllItems();
            editNgay.addItem("Ngày");
            for (int i = 1; i <= (x = 30); i++) {
                String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                editNgay.addItem(dayStr);
            }
        }
        if (!"Ngày".equals(s) && Integer.parseInt(s) <= x) editNgay.setSelectedItem(s);
    }//GEN-LAST:event_editThangActionPerformed

    private void editNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNamActionPerformed
        String s = "Ngày"; int x = 28;
        if(!"Ngày".equals(editNgay.getSelectedItem()))
        s = (String) editNgay.getSelectedItem();

        if ("02".equals(editThang.getSelectedItem())) {
            if(namNhuan(Integer.parseInt((String) editNam.getSelectedItem()))) x = 29;
            editNgay.removeAllItems();
            editNgay.addItem("Ngày");
            for (int i = 1; i <= x; i++) {
                String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                editNgay.addItem(dayStr);
            }
        }
        if (!"Ngày".equals(s) && Integer.parseInt(s) <= x) editNgay.setSelectedItem(s);
    }//GEN-LAST:event_editNamActionPerformed

    private void editGTNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGTNamActionPerformed
        if (editGTNam.isSelected()) editGTNu.setSelected(false);
    }//GEN-LAST:event_editGTNamActionPerformed

    private void editGTNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGTNuActionPerformed
        if (editGTNu.isSelected()) editGTNam.setSelected(false);
    }//GEN-LAST:event_editGTNuActionPerformed

    private void editSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editSDTFocusGained
        if(editSDT.getText().equals("Nhập Số Điện Thoại")){
            editSDT.setText("");
            editSDT.setForeground(new Color(40,40,40));
        }
    }//GEN-LAST:event_editSDTFocusGained

    private void editSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editSDTFocusLost
        if(editSDT.getText().equals("")){
            editSDT.setText("Nhập Số Điện Thoại");
            editSDT.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_editSDTFocusLost

    private void editSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSDTActionPerformed

    private void editMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editMailFocusGained
        if(editMail.getText().equals("Nhập Mail")){
            editMail.setText("");
            editMail.setForeground(new Color(40,40,40));
        }
    }//GEN-LAST:event_editMailFocusGained

    private void editMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editMailFocusLost
        if(editMail.getText().equals("")){
            editMail.setText("Nhập Mail");
            editMail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_editMailFocusLost

    private void editMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDSua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NutHuy;
    private javax.swing.JButton NutSua;
    private javax.swing.JRadioButton editGTNam;
    private javax.swing.JRadioButton editGTNu;
    private javax.swing.JTextField editHoTen;
    private javax.swing.JLabel editMaSV;
    private javax.swing.JTextField editMail;
    private javax.swing.JComboBox<String> editNam;
    private javax.swing.JComboBox<String> editNgay;
    private javax.swing.JTextField editSDT;
    private javax.swing.JComboBox<String> editThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
