/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vovanngoc_n21dcat035;
import java.awt.Color;
import java.awt.List;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ngocn
 */
public class GDThem extends javax.swing.JFrame {

    /**
     * Creates new form GDThem
     */
    private Point initialClick;
    
    public GDThem() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                // Lấy tọa độ chuột khi nhấn
                initialClick = e.getPoint();
            }
            
        });
        jPanel1.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                // Lấy tọa độ chuột khi kéo
                int x = getLocation().x + e.getX() - initialClick.x;
                int y = getLocation().y + e.getY() - initialClick.y;

                // Di chuyển cửa sổ đến vị trí mới
                setLocation(x, y);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public static boolean namNhuan(int y) {
    if ((y % 4 == 0 && y % 100 != 0) || y % 400 == 0) {
        return true;
    } else {
        return false;
    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addMaSV = new javax.swing.JTextField();
        addHoTen = new javax.swing.JTextField();
        addNgay = new javax.swing.JComboBox<>();
        addThang = new javax.swing.JComboBox<>();
        addNam = new javax.swing.JComboBox<>();
        addGTNam = new javax.swing.JRadioButton();
        addGTNu = new javax.swing.JRadioButton();
        addSDT = new javax.swing.JTextField();
        addMail = new javax.swing.JTextField();
        NutHuy = new javax.swing.JButton();
        NutLuu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        jPanel1.setToolTipText("");
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM SINH VIÊN");

        addMaSV.setForeground(new java.awt.Color(153, 153, 153));
        addMaSV.setText("Nhập Mã Sinh Viên");
        addMaSV.setToolTipText("Nhập Mã Sinh Viên");
        addMaSV.setActionCommand("<Not Set>");
        addMaSV.setName(""); // NOI18N
        addMaSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addMaSVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addMaSVFocusLost(evt);
            }
        });
        addMaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaSVActionPerformed(evt);
            }
        });

        addHoTen.setForeground(new java.awt.Color(153, 153, 153));
        addHoTen.setText("Nhập Họ Và Tên");
        addHoTen.setToolTipText("Nhập Họ Và Tên");
        addHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addHoTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addHoTenFocusLost(evt);
            }
        });
        addHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHoTenActionPerformed(evt);
            }
        });

        addNgay.setMaximumRowCount(32);
        addNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        addNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNgayActionPerformed(evt);
            }
        });
        addNgay.setMaximumRowCount(10);
        for(int i = 1; i <= 31; i++){
            if(i < 10) addNgay.addItem("0" + String.valueOf(i));
            else addNgay.addItem(String.valueOf(i));
        }

        addThang.setMaximumRowCount(13);
        addThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng" }));
        addThang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addThangFocusGained(evt);
            }
        });
        addThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addThangActionPerformed(evt);
            }
        });
        for(int i = 1; i <= 12; i++){
            if(i < 10) addThang.addItem("0" + String.valueOf(i));
            else addThang.addItem(String.valueOf(i));
        }
        addThang.setMaximumRowCount(10);

        addNam.setMaximumRowCount(100);
        addNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm" }));
        addNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNamActionPerformed(evt);
            }
        });
        for(int i = 0; i <= 100; i++){
            addNam.addItem(String.valueOf(2023 - i));
        }
        addNam.setMaximumRowCount(10);

        addGTNam.setText("Nam");
        addGTNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGTNamActionPerformed(evt);
            }
        });

        addGTNu.setText("Nữ");
        addGTNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGTNuActionPerformed(evt);
            }
        });

        addSDT.setForeground(new java.awt.Color(153, 153, 153));
        addSDT.setText("Nhập Số Điện Thoại");
        addSDT.setToolTipText("Nhập Số Điện Thoại");
        addSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addSDTFocusLost(evt);
            }
        });
        addSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSDTActionPerformed(evt);
            }
        });

        addMail.setForeground(new java.awt.Color(153, 153, 153));
        addMail.setText("Nhập Mail");
        addMail.setToolTipText("Nhập Mail");
        addMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addMailFocusLost(evt);
            }
        });
        addMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMailActionPerformed(evt);
            }
        });

        NutHuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NutHuy.setText("Hủy");
        NutHuy.setMargin(new java.awt.Insets(3, 3, 3, 3));
        NutHuy.setMaximumSize(new java.awt.Dimension(38, 28));
        NutHuy.setMinimumSize(new java.awt.Dimension(38, 28));
        NutHuy.setPreferredSize(new java.awt.Dimension(60, 27));
        NutHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutHuyActionPerformed(evt);
            }
        });

        NutLuu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NutLuu.setText("Lưu");
        NutLuu.setMargin(new java.awt.Insets(3, 3, 3, 3));
        NutLuu.setMaximumSize(new java.awt.Dimension(38, 28));
        NutLuu.setMinimumSize(new java.awt.Dimension(38, 28));
        NutLuu.setPreferredSize(new java.awt.Dimension(60, 27));
        NutLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutLuuActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày Sinh:");

        jLabel3.setText("Giới Tính:");

        setTitle("Custom TextField Example");
        //addMaSV.setPromptText("Mã Sinh Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NutLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NutHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addMaSV)
                    .addComponent(addHoTen)
                    .addComponent(addSDT)
                    .addComponent(addMail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addThang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addNam, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addGTNam)
                        .addGap(18, 18, 18)
                        .addComponent(addGTNu)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGTNam)
                    .addComponent(addGTNu)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(addNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NutHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NutLuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        addMaSV.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNgayActionPerformed

    private void NutLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutLuuActionPerformed
        String maChuan = "[nbNB]\\d{2}[A-Za-z]{4}\\d{3}";
        String sdtChuan = "[0-9]{10}";
        String mailChuan = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        if("Nhập Mã Sinh Viên".equals(addMaSV.getText()) || "Nhập Họ Và Tên".equals(addHoTen.getText()) 
                || "Ngày".equals(addNgay.getSelectedItem()) || "Tháng".equals(addThang.getSelectedItem()) 
                || "Năm".equals(addNam.getSelectedItem()) || (!addGTNu.isSelected() && !addGTNam.isSelected())
            || "Nhập Số Điện Thoại".equals(addSDT.getText()) || "Nhập Mail".equals(addMail.getText())){
            JOptionPane.showMessageDialog(this, "Không để trống thông tin!!!");
        }
        else if(!addMaSV.getText().matches(maChuan)){
            JOptionPane.showMessageDialog(this, "Mã sinh Viên không đúng định dạng!!!");
        }else if(!addSDT.getText().matches(sdtChuan)){
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng!!!");
        }else if(!addMail.getText().matches(mailChuan)){
            JOptionPane.showMessageDialog(this, "Mail không đúng định dạng!!!");
        }
        else{
            String ns = addNam.getSelectedItem() + "-" + addThang.getSelectedItem() + "-" +addNgay.getSelectedItem();
            byte gt;
            if(addGTNam.isSelected()) gt = 1;
            else gt = 0;
            XuLySQL.luuSV(addMaSV.getText(), addHoTen.getText(), ns, gt, addSDT.getText(), addMail.getText());
            if(XuLySQL.loiLuu == 1){
                JOptionPane.showMessageDialog(this, "Mã sinh viên " + addMaSV.getText() + " đã tồn tại!!!");
            }else if(XuLySQL.loiLuu == 2){
                JOptionPane.showMessageDialog(this, "Số điện thoại " + addSDT.getText() + " đã tồn tại!!!");
            }else if(XuLySQL.loiLuu == 3){
                JOptionPane.showMessageDialog(this, "Mail " + addMail.getText() + " đã tồn tại!!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                dispose();
                addMaSV.setText(""); addHoTen.setText(""); 
                addNgay.setSelectedItem("");; addThang.setSelectedItem(""); addNam.setSelectedItem("");
                addGTNam.setSelected(false); addGTNu.setSelected(false); addSDT.setText(""); addMail.setText("");
            }
        }
    }//GEN-LAST:event_NutLuuActionPerformed

    private void NutHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutHuyActionPerformed
        dispose();
    }//GEN-LAST:event_NutHuyActionPerformed

    private void addMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMailActionPerformed

    private void addSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSDTActionPerformed

    private void addGTNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGTNuActionPerformed
        if (addGTNu.isSelected()) addGTNam.setSelected(false);
    }//GEN-LAST:event_addGTNuActionPerformed

    private void addGTNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGTNamActionPerformed
        if (addGTNam.isSelected()) addGTNu.setSelected(false);
    }//GEN-LAST:event_addGTNamActionPerformed

    private void addHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHoTenActionPerformed

    private void addMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaSVActionPerformed

    private void addMaSVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addMaSVFocusGained
        if(addMaSV.getText().equals("Nhập Mã Sinh Viên")){
            addMaSV.setText("");
            addMaSV.setForeground(new Color(40,40,40));
        }
    }//GEN-LAST:event_addMaSVFocusGained

    private void addThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addThangActionPerformed
        String s = "Ngày"; int x = 29;
        if(!"Ngày".equals(addNgay.getSelectedItem()))
            s = (String) addNgay.getSelectedItem();
        if ("02".equals(addThang.getSelectedItem())) {
            if(!"Năm".equals(addNam.getSelectedItem()))
            x = namNhuan(Integer.parseInt((String) addNam.getSelectedItem())) ? 29 : 28;
                addNgay.removeAllItems();
                addNgay.addItem("Ngày");
                
                for (int i = 1; i <= x; i++) {
                    String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                    addNgay.addItem(dayStr);
                }
            
        }
        var t31 = Arrays.asList("01", "03", "05", "07", "08", "10", "12");
        if (t31.contains(addThang.getSelectedItem())) {
            addNgay.removeAllItems();
            addNgay.addItem("Ngày");    
            for (int i = 1; i <= (x = 31); i++) {
                String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                addNgay.addItem(dayStr);
            }
        }
        var t30 = Arrays.asList("04", "06", "09", "11");
        if (t30.contains(addThang.getSelectedItem())) {
            addNgay.removeAllItems();
            addNgay.addItem("Ngày");    
            for (int i = 1; i <= (x = 30); i++) {
                String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                addNgay.addItem(dayStr);
            }
        }
        if (!"Ngày".equals(s) && Integer.parseInt(s) <= x) addNgay.setSelectedItem(s);
    }//GEN-LAST:event_addThangActionPerformed

    private void addNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNamActionPerformed
        String s = "Ngày"; int x = 28;
        if(!"Ngày".equals(addNgay.getSelectedItem()))
            s = (String) addNgay.getSelectedItem();
        
        if ("02".equals(addThang.getSelectedItem())) {
            if(namNhuan(Integer.parseInt((String) addNam.getSelectedItem()))) x = 29;
            addNgay.removeAllItems();
            addNgay.addItem("Ngày");
            for (int i = 1; i <= x; i++) {
                String dayStr = (i < 10) ? "0" + String.valueOf(i) : String.valueOf(i);
                addNgay.addItem(dayStr);
            } 
        }
        if (!"Ngày".equals(s) && Integer.parseInt(s) <= x) addNgay.setSelectedItem(s);
    }//GEN-LAST:event_addNamActionPerformed

    private void addThangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addThangFocusGained
        
    }//GEN-LAST:event_addThangFocusGained

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
      
    }//GEN-LAST:event_jPanel1MouseDragged

    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
    }//GEN-LAST:event_formMouseDragged

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded

    }//GEN-LAST:event_jPanel1AncestorAdded

    private void addMaSVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addMaSVFocusLost
        if(addMaSV.getText().equals("")){
            addMaSV.setText("Nhập Mã Sinh Viên");
            addMaSV.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_addMaSVFocusLost

    private void addHoTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addHoTenFocusGained
        if(addHoTen.getText().equals("Nhập Họ Và Tên")){
            addHoTen.setText("");
            addHoTen.setForeground(new Color(40,40,40));
        }
    }//GEN-LAST:event_addHoTenFocusGained

    private void addHoTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addHoTenFocusLost
        if(addHoTen.getText().equals("")){
            addHoTen.setText("Nhập Họ Và Tên");
            addHoTen.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_addHoTenFocusLost

    private void addSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addSDTFocusGained
        if(addSDT.getText().equals("Nhập Số Điện Thoại")){
            addSDT.setText("");
            addSDT.setForeground(new Color(40,40,40));
        }
    }//GEN-LAST:event_addSDTFocusGained

    private void addSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addSDTFocusLost
        if(addSDT.getText().equals("")){
            addSDT.setText("Nhập Số Điện Thoại");
            addSDT.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_addSDTFocusLost

    private void addMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addMailFocusGained
        if(addMail.getText().equals("Nhập Mail")){
            addMail.setText("");
            addMail.setForeground(new Color(40,40,40));
        }
    }//GEN-LAST:event_addMailFocusGained

    private void addMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addMailFocusLost
        if(addMail.getText().equals("")){
            addMail.setText("Nhập Mail");
            addMail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_addMailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                GDThem GDT = new GDThem();
                GDT.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NutHuy;
    private javax.swing.JButton NutLuu;
    private javax.swing.JRadioButton addGTNam;
    private javax.swing.JRadioButton addGTNu;
    private javax.swing.JTextField addHoTen;
    private javax.swing.JTextField addMaSV;
    private javax.swing.JTextField addMail;
    private javax.swing.JComboBox<String> addNam;
    private javax.swing.JComboBox<String> addNgay;
    private javax.swing.JTextField addSDT;
    private javax.swing.JComboBox<String> addThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
