/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vovanngoc_n21dcat035;

import ChucNang.Action;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author ngocn
 */
public class GDXem extends javax.swing.JFrame {

    /**
     * Creates new form GDXem
     */
    private Point initialClick;
    

    
    public GDXem() {
        setUndecorated(true);
        setResizable(false);
        
        initComponents();
jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                // Lấy tọa độ chuột khi nhấn
                initialClick = e.getPoint();
            }
            
        });
        jPanel1.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                // Lấy tọa độ chuột khi kéo
                int x = getLocation().x + e.getX() - initialClick.x;
                int y = getLocation().y + e.getY() - initialClick.y;

                // Di chuyển cửa sổ đến vị trí mới
                setLocation(x, y);
            }
        });
    }

    public JLabel getXemMaSV() {
        return xemMaSV;
    }

    public void layThongTin(int row) {
        xemMaSV.setText("Mã sinh viên: ");
        xemHoTen.setText("Họ và tên: ");
        xemNgaySinh.setText("Ngày sinh: ");
        xemGioiTinh.setText("Giới tính: ");
        xemSDT.setText("Số điện thoại: ");
        xemMail.setText("Mail: ");
        xemMaSV.setText(xemMaSV.getText() + GiaoDienChinh.dtm.getValueAt(row, 0));
        xemHoTen.setText(xemHoTen.getText() + GiaoDienChinh.dtm.getValueAt(row, 1));
        String ns = (String) GiaoDienChinh.dtm.getValueAt(row, 2);
        String[] ngay = ns.split("-");
        xemNgaySinh.setText(xemNgaySinh.getText() + ngay[2] + "/" + ngay[1] + "/" + ngay[0]);
        if((Byte) GiaoDienChinh.dtm.getValueAt(row, 3) == 1) {
            xemGioiTinh.setText(xemGioiTinh.getText() + "Nam");
        } else {
            xemGioiTinh.setText(xemGioiTinh.getText() + "Nữ");
        }
        xemSDT.setText(xemSDT.getText() + GiaoDienChinh.dtm.getValueAt(row, 4));
        xemMail.setText(xemMail.getText() + GiaoDienChinh.dtm.getValueAt(row, 5));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xemHoTen2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xemMaSV = new javax.swing.JLabel();
        xemNgaySinh = new javax.swing.JLabel();
        xemSDT = new javax.swing.JLabel();
        xemGioiTinh = new javax.swing.JLabel();
        xemHoTen = new javax.swing.JLabel();
        xemMail = new javax.swing.JLabel();
        NutDong = new javax.swing.JButton();

        xemHoTen2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemHoTen2.setText("Họ và tên: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN SINH VIÊN");

        xemMaSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemMaSV.setText("Mã sinh viên: ");

        xemNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemNgaySinh.setText("Ngày sinh: ");

        xemSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemSDT.setText("Số điện thoại: ");

        xemGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemGioiTinh.setText("Giới tính: ");

        xemHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemHoTen.setText("Họ và tên: ");

        xemMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xemMail.setText("Mail: ");

        NutDong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NutDong.setText("Đóng");
        NutDong.setMargin(new java.awt.Insets(3, 3, 3, 3));
        NutDong.setMaximumSize(new java.awt.Dimension(38, 28));
        NutDong.setMinimumSize(new java.awt.Dimension(38, 28));
        NutDong.setPreferredSize(new java.awt.Dimension(60, 27));
        NutDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xemNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(xemHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 12, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xemSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xemGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(xemMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xemMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NutDong, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xemMaSV)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(xemHoTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xemNgaySinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xemMail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(xemGioiTinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xemSDT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NutDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NutDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutDongActionPerformed

        dispose();
        xemMaSV.setText("Mã sinh viên: ");
        xemHoTen.setText("Họ và tên: ");
        xemNgaySinh.setText("Ngày sinh: ");
        xemGioiTinh.setText("Giới tính: ");
        xemSDT.setText("Số điện thoại: ");
        xemMail.setText("Mail: ");
    }//GEN-LAST:event_NutDongActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded

    }//GEN-LAST:event_jPanel1AncestorAdded

    
    
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
 
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDXem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDXem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDXem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDXem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDXem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NutDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel xemGioiTinh;
    private javax.swing.JLabel xemHoTen;
    private javax.swing.JLabel xemHoTen2;
    private javax.swing.JLabel xemMaSV;
    private javax.swing.JLabel xemMail;
    private javax.swing.JLabel xemNgaySinh;
    private javax.swing.JLabel xemSDT;
    // End of variables declaration//GEN-END:variables
}
